version: '3'
services:
  db:
    image: postgres:15
    container_name: postgres
    environment:
    - POSTGRES_USER=odoo
    - POSTGRES_PASSWORD=odoo16@2022
    networks:
    - odoo1-network
    volumes:
    - ./postgresql:/var/lib/postgresql/data
    restart: on-failure:5

  odoo1:
    image: odoo:latest
    container_name: odoo1
    depends_on:
    - db
    ports:
    - "8069:8069"
     # - "20016:8072" # live chat
    tty: true
    command: --dev=all
    environment:
    - HOST=db
    - USER=odoo
    - PASSWORD=odoo16@2022
    volumes:
    - ./odoo1/addons:/mnt/extra-addons
    - ./odoo1/etc:/etc/odoo
    networks:
    - odoo1-network
    restart: on-failure:5

networks:
  odoo1-network:
    driver: bridge
    name: odoo1-network
  
